//! Built-in catalog with 120+ curated MCP servers and Skills.
//! Organized by category for the AgentShield store.

pub struct CatalogEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub safety_level: &'static str,
    pub rating: f32,
    pub install_count: u32,
    pub npx_pkg: &'static str,
    pub featured: bool,
    pub icon: &'static str,
    pub item_type: &'static str, // "mcp" or "skill"
    pub category: &'static str,
}

// ═══════════════════════════════════════════════════════════════
// OpenClaw 专区 (featured = true) — 核心推荐
// ═══════════════════════════════════════════════════════════════

pub const OPENCLAW_FEATURED: &[CatalogEntry] = &[
    CatalogEntry {
        id: "filesystem",
        name: "Filesystem",
        description: "Secure file system access with configurable allowed directories",
        safety_level: "caution",
        rating: 4.8,
        install_count: 52000,
        npx_pkg: "@modelcontextprotocol/server-filesystem",
        featured: true,
        icon: "folder",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "github",
        name: "GitHub",
        description: "GitHub API integration for repositories, issues, and pull requests",
        safety_level: "caution",
        rating: 4.9,
        install_count: 48000,
        npx_pkg: "@modelcontextprotocol/server-github",
        featured: true,
        icon: "github",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "memory",
        name: "Memory",
        description: "Persistent knowledge graph memory for long-term context retention",
        safety_level: "safe",
        rating: 4.7,
        install_count: 38000,
        npx_pkg: "@modelcontextprotocol/server-memory",
        featured: true,
        icon: "brain",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "sequential-thinking",
        name: "Sequential Thinking",
        description: "Step-by-step reasoning and structured problem-solving",
        safety_level: "safe",
        rating: 4.9,
        install_count: 42000,
        npx_pkg: "@modelcontextprotocol/server-sequential-thinking",
        featured: true,
        icon: "brain",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "fetch",
        name: "Fetch",
        description: "HTTP client for fetching and converting web content to Markdown",
        safety_level: "safe",
        rating: 4.5,
        install_count: 35000,
        npx_pkg: "@modelcontextprotocol/server-fetch",
        featured: true,
        icon: "download",
        item_type: "mcp",
        category: "web-apis",
    },
    CatalogEntry {
        id: "brave-search",
        name: "Brave Search",
        description: "Web and local search via Brave Search API with privacy focus",
        safety_level: "safe",
        rating: 4.8,
        install_count: 41000,
        npx_pkg: "@modelcontextprotocol/server-brave-search",
        featured: true,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "puppeteer",
        name: "Puppeteer",
        description: "Browser automation for web scraping, screenshots, and testing",
        safety_level: "caution",
        rating: 4.7,
        install_count: 36000,
        npx_pkg: "@modelcontextprotocol/server-puppeteer",
        featured: true,
        icon: "globe",
        item_type: "mcp",
        category: "web-apis",
    },
    CatalogEntry {
        id: "postgres",
        name: "PostgreSQL",
        description: "Read-only access to PostgreSQL databases with schema inspection",
        safety_level: "caution",
        rating: 4.6,
        install_count: 32000,
        npx_pkg: "@modelcontextprotocol/server-postgres",
        featured: true,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "sqlite",
        name: "SQLite",
        description: "Local SQLite database operations with business intelligence queries",
        safety_level: "safe",
        rating: 4.5,
        install_count: 28000,
        npx_pkg: "@modelcontextprotocol/server-sqlite",
        featured: true,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "git",
        name: "Git",
        description: "Git repository operations including clone, diff, log, and commit",
        safety_level: "caution",
        rating: 4.7,
        install_count: 34000,
        npx_pkg: "@modelcontextprotocol/server-git",
        featured: true,
        icon: "git-branch",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "google-maps",
        name: "Google Maps",
        description: "Google Maps geocoding, directions, places, and distance calculations",
        safety_level: "safe",
        rating: 4.6,
        install_count: 25000,
        npx_pkg: "@modelcontextprotocol/server-google-maps",
        featured: true,
        icon: "map-pin",
        item_type: "mcp",
        category: "web-apis",
    },
    CatalogEntry {
        id: "slack",
        name: "Slack",
        description: "Slack workspace integration for channels, messages, and users",
        safety_level: "caution",
        rating: 4.6,
        install_count: 29000,
        npx_pkg: "@modelcontextprotocol/server-slack",
        featured: true,
        icon: "message-square",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "everything",
        name: "Everything",
        description: "MCP reference server demonstrating all protocol features and capabilities",
        safety_level: "safe",
        rating: 4.4,
        install_count: 18000,
        npx_pkg: "@modelcontextprotocol/server-everything",
        featured: true,
        icon: "package",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "context7",
        name: "Context7",
        description: "Up-to-date library documentation and code examples for any framework",
        safety_level: "safe",
        rating: 4.8,
        install_count: 39000,
        npx_pkg: "context7-mcp",
        featured: true,
        icon: "book-open",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "tavily",
        name: "Tavily Search",
        description: "AI-optimized web search, extract, crawl, and research capabilities",
        safety_level: "safe",
        rating: 4.7,
        install_count: 33000,
        npx_pkg: "tavily-mcp",
        featured: true,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
];

// ═══════════════════════════════════════════════════════════════
// 数据库与存储 (Database & Storage)
// ═══════════════════════════════════════════════════════════════

pub const DATABASE_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "mysql",
        name: "MySQL",
        description: "MySQL database operations with schema inspection and query execution",
        safety_level: "caution",
        rating: 4.5,
        install_count: 22000,
        npx_pkg: "mysql-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "mongodb",
        name: "MongoDB",
        description: "MongoDB database operations with collection management and queries",
        safety_level: "caution",
        rating: 4.4,
        install_count: 19000,
        npx_pkg: "mongodb-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "redis",
        name: "Redis",
        description: "Redis key-value store operations with pub/sub and data structures",
        safety_level: "caution",
        rating: 4.5,
        install_count: 20000,
        npx_pkg: "redis-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "supabase",
        name: "Supabase",
        description: "Supabase backend-as-a-service with database, auth, and storage",
        safety_level: "caution",
        rating: 4.7,
        install_count: 26000,
        npx_pkg: "supabase-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "neon",
        name: "Neon",
        description: "Neon serverless PostgreSQL with branching and connection management",
        safety_level: "caution",
        rating: 4.5,
        install_count: 15000,
        npx_pkg: "@neondatabase/mcp-server-neon",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "planetscale",
        name: "PlanetScale",
        description: "PlanetScale serverless MySQL with branching and deploy requests",
        safety_level: "caution",
        rating: 4.4,
        install_count: 12000,
        npx_pkg: "planetscale-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "turso",
        name: "Turso",
        description: "Turso embedded SQLite replicas with edge distribution",
        safety_level: "caution",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "turso-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "elasticsearch",
        name: "Elasticsearch",
        description: "Elasticsearch search and analytics engine with index management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "elasticsearch-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "qdrant",
        name: "Qdrant",
        description: "Qdrant vector database for similarity search and embeddings",
        safety_level: "caution",
        rating: 4.4,
        install_count: 14000,
        npx_pkg: "qdrant-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
    CatalogEntry {
        id: "pinecone",
        name: "Pinecone",
        description: "Pinecone vector database for AI embeddings and semantic search",
        safety_level: "caution",
        rating: 4.3,
        install_count: 12000,
        npx_pkg: "pinecone-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "database",
    },
];

// ═══════════════════════════════════════════════════════════════
// 开发工具 (Development Tools)
// ═══════════════════════════════════════════════════════════════

pub const DEV_TOOLS_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "docker",
        name: "Docker",
        description: "Docker container management, images, and compose operations",
        safety_level: "caution",
        rating: 4.6,
        install_count: 27000,
        npx_pkg: "docker-mcp-server",
        featured: false,
        icon: "box",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "kubernetes",
        name: "Kubernetes",
        description: "Kubernetes cluster management with pods, services, and deployments",
        safety_level: "caution",
        rating: 4.5,
        install_count: 18000,
        npx_pkg: "kubernetes-mcp-server",
        featured: false,
        icon: "server",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "gitlab",
        name: "GitLab",
        description: "GitLab API for repositories, merge requests, pipelines, and issues",
        safety_level: "caution",
        rating: 4.5,
        install_count: 16000,
        npx_pkg: "gitlab-mcp-server",
        featured: false,
        icon: "git-branch",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "linear",
        name: "Linear",
        description: "Linear project management with issues, projects, and team workflows",
        safety_level: "caution",
        rating: 4.6,
        install_count: 19000,
        npx_pkg: "linear-mcp-server",
        featured: false,
        icon: "layout",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "jira",
        name: "Jira",
        description: "Atlassian Jira issue tracking, sprints, and project management",
        safety_level: "caution",
        rating: 4.4,
        install_count: 15000,
        npx_pkg: "jira-mcp-server",
        featured: false,
        icon: "clipboard",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "sentry",
        name: "Sentry",
        description: "Sentry error tracking and performance monitoring integration",
        safety_level: "caution",
        rating: 4.5,
        install_count: 17000,
        npx_pkg: "sentry-mcp-server",
        featured: false,
        icon: "alert-triangle",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "playwright",
        name: "Playwright",
        description: "Browser automation and end-to-end testing with Playwright",
        safety_level: "caution",
        rating: 4.6,
        install_count: 21000,
        npx_pkg: "@anthropic/mcp-server-playwright",
        featured: false,
        icon: "monitor",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "npm",
        name: "NPM",
        description: "NPM package search, info, and dependency management",
        safety_level: "safe",
        rating: 4.3,
        install_count: 13000,
        npx_pkg: "npm-mcp-server",
        featured: false,
        icon: "package",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "postman",
        name: "Postman",
        description: "Postman API testing collections and environment management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "postman-mcp-server",
        featured: false,
        icon: "send",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "circleci",
        name: "CircleCI",
        description: "CircleCI pipeline management, builds, and deployment automation",
        safety_level: "caution",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "circleci-mcp-server",
        featured: false,
        icon: "refresh-cw",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "github-actions",
        name: "GitHub Actions",
        description: "GitHub Actions workflow management and CI/CD automation",
        safety_level: "caution",
        rating: 4.5,
        install_count: 16000,
        npx_pkg: "github-actions-mcp-server",
        featured: false,
        icon: "play-circle",
        item_type: "mcp",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "raygun",
        name: "Raygun",
        description: "Raygun crash reporting and real user monitoring",
        safety_level: "caution",
        rating: 4.1,
        install_count: 5000,
        npx_pkg: "raygun-mcp-server",
        featured: false,
        icon: "zap",
        item_type: "mcp",
        category: "dev-tools",
    },
];

// ═══════════════════════════════════════════════════════════════
// 搜索与知识 (Search & Knowledge)
// ═══════════════════════════════════════════════════════════════

pub const SEARCH_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "google-search",
        name: "Google Search",
        description: "Google Custom Search API for web search results",
        safety_level: "safe",
        rating: 4.6,
        install_count: 28000,
        npx_pkg: "google-search-mcp-server",
        featured: false,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "exa",
        name: "Exa",
        description: "Exa neural search engine for semantic web search and content",
        safety_level: "safe",
        rating: 4.5,
        install_count: 18000,
        npx_pkg: "exa-mcp-server",
        featured: false,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "arxiv",
        name: "arXiv",
        description: "Search and retrieve academic papers from arXiv repository",
        safety_level: "safe",
        rating: 4.4,
        install_count: 12000,
        npx_pkg: "arxiv-mcp-server",
        featured: false,
        icon: "book",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "wikipedia",
        name: "Wikipedia",
        description: "Wikipedia article search, summaries, and content extraction",
        safety_level: "safe",
        rating: 4.5,
        install_count: 15000,
        npx_pkg: "wikipedia-mcp-server",
        featured: false,
        icon: "book-open",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "perplexity",
        name: "Perplexity",
        description: "Perplexity AI search for real-time information with citations",
        safety_level: "safe",
        rating: 4.6,
        install_count: 20000,
        npx_pkg: "perplexity-mcp-server",
        featured: false,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "duckduckgo",
        name: "DuckDuckGo",
        description: "Privacy-first web search via DuckDuckGo API",
        safety_level: "safe",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "duckduckgo-mcp-server",
        featured: false,
        icon: "search",
        item_type: "mcp",
        category: "search",
    },
    CatalogEntry {
        id: "rag-web-browser",
        name: "RAG Web Browser",
        description: "Web browsing with RAG for research and content extraction",
        safety_level: "safe",
        rating: 4.4,
        install_count: 11000,
        npx_pkg: "rag-web-browser-mcp",
        featured: false,
        icon: "globe",
        item_type: "mcp",
        category: "search",
    },
];

// ═══════════════════════════════════════════════════════════════
// 云服务与基础设施 (Cloud & Infrastructure)
// ═══════════════════════════════════════════════════════════════

pub const CLOUD_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "aws",
        name: "AWS",
        description: "Amazon Web Services integration for S3, Lambda, EC2, and more",
        safety_level: "caution",
        rating: 4.6,
        install_count: 23000,
        npx_pkg: "aws-mcp-server",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "cloudflare",
        name: "Cloudflare",
        description: "Cloudflare Workers, KV, R2, D1, and DNS management",
        safety_level: "caution",
        rating: 4.6,
        install_count: 22000,
        npx_pkg: "@anthropic/mcp-server-cloudflare",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "vercel",
        name: "Vercel",
        description: "Vercel deployment management, projects, and serverless functions",
        safety_level: "caution",
        rating: 4.5,
        install_count: 19000,
        npx_pkg: "vercel-mcp-server",
        featured: false,
        icon: "triangle",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "netlify",
        name: "Netlify",
        description: "Netlify site deployment, functions, and build management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "netlify-mcp-server",
        featured: false,
        icon: "globe",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "azure",
        name: "Azure",
        description: "Microsoft Azure services including VMs, storage, and cognitive APIs",
        safety_level: "caution",
        rating: 4.4,
        install_count: 16000,
        npx_pkg: "azure-mcp-server",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "gcp",
        name: "Google Cloud",
        description: "Google Cloud Platform services with BigQuery, GCS, and Compute",
        safety_level: "caution",
        rating: 4.4,
        install_count: 15000,
        npx_pkg: "gcp-mcp-server",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "terraform",
        name: "Terraform",
        description: "Terraform infrastructure-as-code management and planning",
        safety_level: "caution",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "terraform-mcp-server",
        featured: false,
        icon: "layers",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "fly-io",
        name: "Fly.io",
        description: "Fly.io application deployment and machine management",
        safety_level: "caution",
        rating: 4.2,
        install_count: 7000,
        npx_pkg: "fly-mcp-server",
        featured: false,
        icon: "send",
        item_type: "mcp",
        category: "cloud",
    },
    CatalogEntry {
        id: "digitalocean",
        name: "DigitalOcean",
        description: "DigitalOcean droplets, databases, and Kubernetes management",
        safety_level: "caution",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "digitalocean-mcp-server",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "cloud",
    },
];

// ═══════════════════════════════════════════════════════════════
// AI 与 LLM (AI & Machine Learning)
// ═══════════════════════════════════════════════════════════════

pub const AI_ML_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "openai",
        name: "OpenAI",
        description: "OpenAI API for GPT models, DALL-E, Whisper, and embeddings",
        safety_level: "caution",
        rating: 4.7,
        install_count: 31000,
        npx_pkg: "openai-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "anthropic",
        name: "Anthropic Claude",
        description: "Anthropic Claude API for advanced reasoning and analysis",
        safety_level: "caution",
        rating: 4.8,
        install_count: 28000,
        npx_pkg: "anthropic-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "langchain",
        name: "LangChain",
        description: "LangChain framework tools for chain-of-thought and agent workflows",
        safety_level: "caution",
        rating: 4.5,
        install_count: 18000,
        npx_pkg: "langchain-mcp-server",
        featured: false,
        icon: "link",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "huggingface",
        name: "Hugging Face",
        description: "Hugging Face model hub, datasets, and inference API access",
        safety_level: "safe",
        rating: 4.5,
        install_count: 16000,
        npx_pkg: "huggingface-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "replicate",
        name: "Replicate",
        description: "Replicate model hosting and inference for image, video, and audio AI",
        safety_level: "caution",
        rating: 4.4,
        install_count: 14000,
        npx_pkg: "replicate-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "ollama",
        name: "Ollama",
        description: "Local LLM inference with Ollama for private on-device AI",
        safety_level: "safe",
        rating: 4.6,
        install_count: 24000,
        npx_pkg: "ollama-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "stability-ai",
        name: "Stability AI",
        description: "Stable Diffusion and SDXL image generation via Stability API",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "stability-mcp-server",
        featured: false,
        icon: "image",
        item_type: "mcp",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "deepseek",
        name: "DeepSeek",
        description: "DeepSeek AI models for coding, reasoning, and chat",
        safety_level: "caution",
        rating: 4.5,
        install_count: 19000,
        npx_pkg: "deepseek-mcp-server",
        featured: false,
        icon: "cpu",
        item_type: "mcp",
        category: "ai-ml",
    },
];

// ═══════════════════════════════════════════════════════════════
// 通讯协作 (Communication & Collaboration)
// ═══════════════════════════════════════════════════════════════

pub const COMMUNICATION_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "discord",
        name: "Discord",
        description: "Discord bot integration for servers, channels, and message management",
        safety_level: "caution",
        rating: 4.4,
        install_count: 16000,
        npx_pkg: "discord-mcp-server",
        featured: false,
        icon: "message-circle",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "telegram",
        name: "Telegram",
        description: "Telegram bot API for messaging, groups, and channel management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 13000,
        npx_pkg: "telegram-mcp-server",
        featured: false,
        icon: "send",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "email",
        name: "Email (SMTP)",
        description: "Email sending and reading via SMTP and IMAP protocols",
        safety_level: "caution",
        rating: 4.2,
        install_count: 11000,
        npx_pkg: "email-mcp-server",
        featured: false,
        icon: "mail",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "notion",
        name: "Notion",
        description: "Notion workspace with pages, databases, and content management",
        safety_level: "caution",
        rating: 4.7,
        install_count: 30000,
        npx_pkg: "notion-mcp-server",
        featured: false,
        icon: "file-text",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "confluence",
        name: "Confluence",
        description: "Atlassian Confluence wiki pages, spaces, and content management",
        safety_level: "caution",
        rating: 4.2,
        install_count: 9000,
        npx_pkg: "confluence-mcp-server",
        featured: false,
        icon: "book",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "google-drive",
        name: "Google Drive",
        description: "Google Drive file management, search, and sharing",
        safety_level: "caution",
        rating: 4.5,
        install_count: 21000,
        npx_pkg: "@anthropic/mcp-server-gdrive",
        featured: false,
        icon: "hard-drive",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "microsoft-teams",
        name: "Microsoft Teams",
        description: "Microsoft Teams messaging, channels, and meeting management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 12000,
        npx_pkg: "teams-mcp-server",
        featured: false,
        icon: "users",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "google-calendar",
        name: "Google Calendar",
        description: "Google Calendar event management, scheduling, and availability",
        safety_level: "caution",
        rating: 4.4,
        install_count: 16000,
        npx_pkg: "google-calendar-mcp-server",
        featured: false,
        icon: "calendar",
        item_type: "mcp",
        category: "communication",
    },
    CatalogEntry {
        id: "todoist",
        name: "Todoist",
        description: "Todoist task management, projects, and productivity tracking",
        safety_level: "caution",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "todoist-mcp-server",
        featured: false,
        icon: "check-square",
        item_type: "mcp",
        category: "communication",
    },
];

// ═══════════════════════════════════════════════════════════════
// 文件与文档 (File & Document Processing)
// ═══════════════════════════════════════════════════════════════

pub const FILE_DOC_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "pdf-reader",
        name: "PDF Reader",
        description: "PDF parsing, text extraction, and content analysis",
        safety_level: "safe",
        rating: 4.4,
        install_count: 16000,
        npx_pkg: "pdf-mcp-server",
        featured: false,
        icon: "file-text",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "excel",
        name: "Excel",
        description: "Excel spreadsheet reading, writing, and formula support",
        safety_level: "safe",
        rating: 4.3,
        install_count: 12000,
        npx_pkg: "excel-mcp-server",
        featured: false,
        icon: "table",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "markdown",
        name: "Markdown",
        description: "Markdown document processing, rendering, and conversion",
        safety_level: "safe",
        rating: 4.2,
        install_count: 9000,
        npx_pkg: "markdown-mcp-server",
        featured: false,
        icon: "file-text",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "s3",
        name: "AWS S3",
        description: "Amazon S3 object storage with bucket and file operations",
        safety_level: "caution",
        rating: 4.4,
        install_count: 15000,
        npx_pkg: "s3-mcp-server",
        featured: false,
        icon: "hard-drive",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "dropbox",
        name: "Dropbox",
        description: "Dropbox file sync, sharing, and folder management",
        safety_level: "caution",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "dropbox-mcp-server",
        featured: false,
        icon: "hard-drive",
        item_type: "mcp",
        category: "file-management",
    },
    CatalogEntry {
        id: "image-tools",
        name: "Image Tools",
        description: "Image processing, resizing, conversion, and metadata extraction",
        safety_level: "safe",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "image-tools-mcp-server",
        featured: false,
        icon: "image",
        item_type: "mcp",
        category: "file-management",
    },
];

// ═══════════════════════════════════════════════════════════════
// 监控与运维 (Monitoring & Operations)
// ═══════════════════════════════════════════════════════════════

pub const MONITORING_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "datadog",
        name: "Datadog",
        description: "Datadog monitoring, metrics, logs, and APM integration",
        safety_level: "caution",
        rating: 4.4,
        install_count: 14000,
        npx_pkg: "datadog-mcp-server",
        featured: false,
        icon: "activity",
        item_type: "mcp",
        category: "monitoring",
    },
    CatalogEntry {
        id: "grafana",
        name: "Grafana",
        description: "Grafana dashboards, alerts, and data source management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "grafana-mcp-server",
        featured: false,
        icon: "bar-chart",
        item_type: "mcp",
        category: "monitoring",
    },
    CatalogEntry {
        id: "prometheus",
        name: "Prometheus",
        description: "Prometheus metrics querying and alerting rule management",
        safety_level: "caution",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "prometheus-mcp-server",
        featured: false,
        icon: "trending-up",
        item_type: "mcp",
        category: "monitoring",
    },
    CatalogEntry {
        id: "pagerduty",
        name: "PagerDuty",
        description: "PagerDuty incident management and on-call scheduling",
        safety_level: "caution",
        rating: 4.2,
        install_count: 7000,
        npx_pkg: "pagerduty-mcp-server",
        featured: false,
        icon: "bell",
        item_type: "mcp",
        category: "monitoring",
    },
    CatalogEntry {
        id: "uptime-kuma",
        name: "Uptime Kuma",
        description: "Self-hosted uptime monitoring and status page management",
        safety_level: "safe",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "uptime-kuma-mcp-server",
        featured: false,
        icon: "activity",
        item_type: "mcp",
        category: "monitoring",
    },
];

// ═══════════════════════════════════════════════════════════════
// 支付与商业 (Payment & Business)
// ═══════════════════════════════════════════════════════════════

pub const BUSINESS_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "stripe",
        name: "Stripe",
        description: "Stripe payment processing, subscriptions, and billing management",
        safety_level: "caution",
        rating: 4.6,
        install_count: 20000,
        npx_pkg: "stripe-mcp-server",
        featured: false,
        icon: "credit-card",
        item_type: "mcp",
        category: "business",
    },
    CatalogEntry {
        id: "shopify",
        name: "Shopify",
        description: "Shopify store management, products, orders, and inventory",
        safety_level: "caution",
        rating: 4.4,
        install_count: 13000,
        npx_pkg: "shopify-mcp-server",
        featured: false,
        icon: "shopping-bag",
        item_type: "mcp",
        category: "business",
    },
    CatalogEntry {
        id: "hubspot",
        name: "HubSpot",
        description: "HubSpot CRM contacts, deals, companies, and marketing automation",
        safety_level: "caution",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "hubspot-mcp-server",
        featured: false,
        icon: "users",
        item_type: "mcp",
        category: "business",
    },
    CatalogEntry {
        id: "salesforce",
        name: "Salesforce",
        description: "Salesforce CRM with objects, SOQL queries, and workflow management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "salesforce-mcp-server",
        featured: false,
        icon: "briefcase",
        item_type: "mcp",
        category: "business",
    },
    CatalogEntry {
        id: "airtable",
        name: "Airtable",
        description: "Airtable spreadsheet-database with bases, tables, and records",
        safety_level: "caution",
        rating: 4.4,
        install_count: 14000,
        npx_pkg: "airtable-mcp-server",
        featured: false,
        icon: "grid",
        item_type: "mcp",
        category: "business",
    },
];

// ═══════════════════════════════════════════════════════════════
// 安全与合规 (Security & Compliance)
// ═══════════════════════════════════════════════════════════════

pub const SECURITY_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "snyk",
        name: "Snyk",
        description: "Snyk vulnerability scanning for dependencies and container images",
        safety_level: "safe",
        rating: 4.5,
        install_count: 15000,
        npx_pkg: "snyk-mcp-server",
        featured: false,
        icon: "shield",
        item_type: "mcp",
        category: "security",
    },
    CatalogEntry {
        id: "vault",
        name: "HashiCorp Vault",
        description: "HashiCorp Vault secrets management and encryption as a service",
        safety_level: "caution",
        rating: 4.4,
        install_count: 12000,
        npx_pkg: "vault-mcp-server",
        featured: false,
        icon: "lock",
        item_type: "mcp",
        category: "security",
    },
    CatalogEntry {
        id: "semgrep",
        name: "Semgrep",
        description: "Semgrep static analysis for security and code quality scanning",
        safety_level: "safe",
        rating: 4.4,
        install_count: 10000,
        npx_pkg: "semgrep-mcp-server",
        featured: false,
        icon: "shield",
        item_type: "mcp",
        category: "security",
    },
    CatalogEntry {
        id: "trivy",
        name: "Trivy",
        description: "Aqua Trivy vulnerability scanner for containers and IaC",
        safety_level: "safe",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "trivy-mcp-server",
        featured: false,
        icon: "shield",
        item_type: "mcp",
        category: "security",
    },
    CatalogEntry {
        id: "owasp-zap",
        name: "OWASP ZAP",
        description: "OWASP ZAP web application security testing and scanning",
        safety_level: "caution",
        rating: 4.3,
        install_count: 8000,
        npx_pkg: "zap-mcp-server",
        featured: false,
        icon: "shield",
        item_type: "mcp",
        category: "security",
    },
];

// ═══════════════════════════════════════════════════════════════
// 数据分析与可视化 (Data Analytics & Visualization)
// ═══════════════════════════════════════════════════════════════

pub const ANALYTICS_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "google-analytics",
        name: "Google Analytics",
        description: "Google Analytics reporting, metrics, and audience insights",
        safety_level: "caution",
        rating: 4.4,
        install_count: 14000,
        npx_pkg: "google-analytics-mcp-server",
        featured: false,
        icon: "bar-chart-2",
        item_type: "mcp",
        category: "analytics",
    },
    CatalogEntry {
        id: "bigquery",
        name: "BigQuery",
        description: "Google BigQuery data warehouse with SQL queries and datasets",
        safety_level: "caution",
        rating: 4.5,
        install_count: 16000,
        npx_pkg: "bigquery-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "analytics",
    },
    CatalogEntry {
        id: "snowflake",
        name: "Snowflake",
        description: "Snowflake data cloud with SQL queries and data sharing",
        safety_level: "caution",
        rating: 4.4,
        install_count: 13000,
        npx_pkg: "snowflake-mcp-server",
        featured: false,
        icon: "database",
        item_type: "mcp",
        category: "analytics",
    },
    CatalogEntry {
        id: "dbt",
        name: "dbt",
        description: "dbt data transformation and analytics engineering workflows",
        safety_level: "caution",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "dbt-mcp-server",
        featured: false,
        icon: "layers",
        item_type: "mcp",
        category: "analytics",
    },
    CatalogEntry {
        id: "jupyter",
        name: "Jupyter",
        description: "Jupyter notebook execution, kernel management, and cell operations",
        safety_level: "caution",
        rating: 4.4,
        install_count: 15000,
        npx_pkg: "jupyter-mcp-server",
        featured: false,
        icon: "code",
        item_type: "mcp",
        category: "analytics",
    },
];

// ═══════════════════════════════════════════════════════════════
// 社交媒体与内容 (Social Media & Content)
// ═══════════════════════════════════════════════════════════════

pub const SOCIAL_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "twitter",
        name: "Twitter / X",
        description: "Twitter/X API for tweets, search, timelines, and user data",
        safety_level: "caution",
        rating: 4.4,
        install_count: 17000,
        npx_pkg: "twitter-mcp-server",
        featured: false,
        icon: "message-circle",
        item_type: "mcp",
        category: "social",
    },
    CatalogEntry {
        id: "youtube",
        name: "YouTube",
        description: "YouTube video search, channel data, and transcript extraction",
        safety_level: "safe",
        rating: 4.5,
        install_count: 19000,
        npx_pkg: "youtube-mcp-server",
        featured: false,
        icon: "play-circle",
        item_type: "mcp",
        category: "social",
    },
    CatalogEntry {
        id: "reddit",
        name: "Reddit",
        description: "Reddit posts, comments, subreddit browsing, and search",
        safety_level: "safe",
        rating: 4.3,
        install_count: 12000,
        npx_pkg: "reddit-mcp-server",
        featured: false,
        icon: "message-circle",
        item_type: "mcp",
        category: "social",
    },
    CatalogEntry {
        id: "hackernews",
        name: "Hacker News",
        description: "Hacker News stories, comments, and trending tech news",
        safety_level: "safe",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "hackernews-mcp-server",
        featured: false,
        icon: "trending-up",
        item_type: "mcp",
        category: "social",
    },
    CatalogEntry {
        id: "medium",
        name: "Medium",
        description: "Medium articles search, reading, and publication management",
        safety_level: "safe",
        rating: 4.1,
        install_count: 6000,
        npx_pkg: "medium-mcp-server",
        featured: false,
        icon: "edit",
        item_type: "mcp",
        category: "social",
    },
];

// ═══════════════════════════════════════════════════════════════
// 设计与创意 (Design & Creative)
// ═══════════════════════════════════════════════════════════════

pub const DESIGN_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "figma",
        name: "Figma",
        description: "Figma design files, components, and design token extraction",
        safety_level: "safe",
        rating: 4.6,
        install_count: 22000,
        npx_pkg: "figma-mcp-server",
        featured: false,
        icon: "pen-tool",
        item_type: "mcp",
        category: "design",
    },
    CatalogEntry {
        id: "canva",
        name: "Canva",
        description: "Canva design creation and template management",
        safety_level: "caution",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "canva-mcp-server",
        featured: false,
        icon: "image",
        item_type: "mcp",
        category: "design",
    },
    CatalogEntry {
        id: "unsplash",
        name: "Unsplash",
        description: "Unsplash free photo search and download API",
        safety_level: "safe",
        rating: 4.4,
        install_count: 13000,
        npx_pkg: "unsplash-mcp-server",
        featured: false,
        icon: "image",
        item_type: "mcp",
        category: "design",
    },
    CatalogEntry {
        id: "screenshot",
        name: "Screenshot",
        description: "Web page screenshot capture with customizable viewport and format",
        safety_level: "safe",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "screenshot-mcp-server",
        featured: false,
        icon: "camera",
        item_type: "mcp",
        category: "design",
    },
];

// ═══════════════════════════════════════════════════════════════
// 地图与位置 (Maps & Location)
// ═══════════════════════════════════════════════════════════════

pub const MAPS_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "openstreetmap",
        name: "OpenStreetMap",
        description: "OpenStreetMap geocoding, routing, and map data queries",
        safety_level: "safe",
        rating: 4.2,
        install_count: 7000,
        npx_pkg: "openstreetmap-mcp-server",
        featured: false,
        icon: "map",
        item_type: "mcp",
        category: "maps",
    },
    CatalogEntry {
        id: "mapbox",
        name: "Mapbox",
        description: "Mapbox mapping, geocoding, and navigation services",
        safety_level: "safe",
        rating: 4.3,
        install_count: 8000,
        npx_pkg: "mapbox-mcp-server",
        featured: false,
        icon: "map-pin",
        item_type: "mcp",
        category: "maps",
    },
    CatalogEntry {
        id: "weather",
        name: "Weather",
        description: "Weather data, forecasts, and historical climate information",
        safety_level: "safe",
        rating: 4.3,
        install_count: 11000,
        npx_pkg: "weather-mcp-server",
        featured: false,
        icon: "cloud",
        item_type: "mcp",
        category: "maps",
    },
];

// ═══════════════════════════════════════════════════════════════
// 实用工具 (Utilities)
// ═══════════════════════════════════════════════════════════════

pub const UTILITY_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "time",
        name: "Time",
        description: "Time zone conversion, date calculations, and clock utilities",
        safety_level: "safe",
        rating: 4.3,
        install_count: 14000,
        npx_pkg: "@modelcontextprotocol/server-time",
        featured: false,
        icon: "clock",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "calculator",
        name: "Calculator",
        description: "Mathematical calculations, unit conversions, and formulas",
        safety_level: "safe",
        rating: 4.2,
        install_count: 8000,
        npx_pkg: "calculator-mcp-server",
        featured: false,
        icon: "hash",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "qr-code",
        name: "QR Code",
        description: "QR code generation and decoding for text, URLs, and data",
        safety_level: "safe",
        rating: 4.1,
        install_count: 6000,
        npx_pkg: "qrcode-mcp-server",
        featured: false,
        icon: "grid",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "currency",
        name: "Currency Exchange",
        description: "Real-time currency exchange rates and conversion",
        safety_level: "safe",
        rating: 4.2,
        install_count: 7000,
        npx_pkg: "currency-mcp-server",
        featured: false,
        icon: "dollar-sign",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "translation",
        name: "Translation",
        description: "Multi-language translation via DeepL, Google Translate, and more",
        safety_level: "safe",
        rating: 4.4,
        install_count: 15000,
        npx_pkg: "translation-mcp-server",
        featured: false,
        icon: "globe",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "shell",
        name: "Shell",
        description: "System shell command execution with sandboxing and output capture",
        safety_level: "dangerous",
        rating: 4.1,
        install_count: 16000,
        npx_pkg: "shell-mcp-server",
        featured: false,
        icon: "terminal",
        item_type: "mcp",
        category: "utility",
    },
    CatalogEntry {
        id: "clipboard",
        name: "Clipboard",
        description: "System clipboard read/write for text and image content",
        safety_level: "caution",
        rating: 4.0,
        install_count: 5000,
        npx_pkg: "clipboard-mcp-server",
        featured: false,
        icon: "clipboard",
        item_type: "mcp",
        category: "utility",
    },
];

// ═══════════════════════════════════════════════════════════════
// Skill 技能 (OpenClaw 专属)
// ═══════════════════════════════════════════════════════════════

pub const SKILL_CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "skill-code-review",
        name: "Code Review",
        description: "Automated code review with security and quality analysis",
        safety_level: "safe",
        rating: 4.7,
        install_count: 25000,
        npx_pkg: "skill-code-review",
        featured: true,
        icon: "check-circle",
        item_type: "skill",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "skill-tdd",
        name: "Test-Driven Development",
        description: "TDD workflow with test-first methodology and coverage tracking",
        safety_level: "safe",
        rating: 4.6,
        install_count: 18000,
        npx_pkg: "skill-tdd",
        featured: true,
        icon: "check-square",
        item_type: "skill",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "skill-debugging",
        name: "Systematic Debugging",
        description: "Structured debugging workflow with root cause analysis",
        safety_level: "safe",
        rating: 4.7,
        install_count: 22000,
        npx_pkg: "skill-debugging",
        featured: true,
        icon: "bug",
        item_type: "skill",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "skill-brainstorming",
        name: "Brainstorming",
        description: "Creative brainstorming with structured ideation frameworks",
        safety_level: "safe",
        rating: 4.5,
        install_count: 15000,
        npx_pkg: "skill-brainstorming",
        featured: true,
        icon: "lightbulb",
        item_type: "skill",
        category: "ai-ml",
    },
    CatalogEntry {
        id: "skill-frontend-design",
        name: "Frontend Design",
        description: "Production-grade UI component design with modern frameworks",
        safety_level: "safe",
        rating: 4.6,
        install_count: 20000,
        npx_pkg: "skill-frontend-design",
        featured: true,
        icon: "layout",
        item_type: "skill",
        category: "design",
    },
    CatalogEntry {
        id: "skill-mcp-builder",
        name: "MCP Builder",
        description: "Build custom MCP servers with best practices and type safety",
        safety_level: "safe",
        rating: 4.5,
        install_count: 14000,
        npx_pkg: "skill-mcp-builder",
        featured: true,
        icon: "tool",
        item_type: "skill",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "skill-pdf-creator",
        name: "PDF Creator",
        description: "Create, merge, split, and manipulate PDF documents",
        safety_level: "safe",
        rating: 4.4,
        install_count: 12000,
        npx_pkg: "skill-pdf",
        featured: false,
        icon: "file-text",
        item_type: "skill",
        category: "file-management",
    },
    CatalogEntry {
        id: "skill-pptx-creator",
        name: "Presentation Creator",
        description: "Create and edit PowerPoint presentations with rich content",
        safety_level: "safe",
        rating: 4.3,
        install_count: 10000,
        npx_pkg: "skill-pptx",
        featured: false,
        icon: "monitor",
        item_type: "skill",
        category: "file-management",
    },
    CatalogEntry {
        id: "skill-xlsx-creator",
        name: "Spreadsheet Creator",
        description: "Create Excel spreadsheets with formulas and charts",
        safety_level: "safe",
        rating: 4.3,
        install_count: 9000,
        npx_pkg: "skill-xlsx",
        featured: false,
        icon: "table",
        item_type: "skill",
        category: "file-management",
    },
    CatalogEntry {
        id: "skill-docx-creator",
        name: "Document Creator",
        description: "Create and edit Word documents with formatting and styles",
        safety_level: "safe",
        rating: 4.3,
        install_count: 9500,
        npx_pkg: "skill-docx",
        featured: false,
        icon: "file-text",
        item_type: "skill",
        category: "file-management",
    },
    CatalogEntry {
        id: "skill-web-testing",
        name: "Web App Testing",
        description: "Browser-based testing with Playwright for web applications",
        safety_level: "caution",
        rating: 4.5,
        install_count: 13000,
        npx_pkg: "skill-webapp-testing",
        featured: false,
        icon: "monitor",
        item_type: "skill",
        category: "dev-tools",
    },
    CatalogEntry {
        id: "skill-algorithmic-art",
        name: "Algorithmic Art",
        description: "Generate algorithmic art with p5.js and creative coding",
        safety_level: "safe",
        rating: 4.2,
        install_count: 7000,
        npx_pkg: "skill-algorithmic-art",
        featured: false,
        icon: "pen-tool",
        item_type: "skill",
        category: "design",
    },
    CatalogEntry {
        id: "skill-doc-coauthoring",
        name: "Doc Co-authoring",
        description: "Collaborative documentation writing with structured workflow",
        safety_level: "safe",
        rating: 4.4,
        install_count: 11000,
        npx_pkg: "skill-doc-coauthoring",
        featured: false,
        icon: "edit",
        item_type: "skill",
        category: "file-management",
    },
];

// ═══════════════════════════════════════════════════════════════
// Aggregate: all categories into one vec
// ═══════════════════════════════════════════════════════════════

pub fn all_builtin_entries() -> Vec<&'static CatalogEntry> {
    let mut v: Vec<&CatalogEntry> = Vec::with_capacity(130);
    for e in OPENCLAW_FEATURED {
        v.push(e);
    }
    for e in DATABASE_CATALOG {
        v.push(e);
    }
    for e in DEV_TOOLS_CATALOG {
        v.push(e);
    }
    for e in SEARCH_CATALOG {
        v.push(e);
    }
    for e in CLOUD_CATALOG {
        v.push(e);
    }
    for e in AI_ML_CATALOG {
        v.push(e);
    }
    for e in COMMUNICATION_CATALOG {
        v.push(e);
    }
    for e in FILE_DOC_CATALOG {
        v.push(e);
    }
    for e in MONITORING_CATALOG {
        v.push(e);
    }
    for e in BUSINESS_CATALOG {
        v.push(e);
    }
    for e in SECURITY_CATALOG {
        v.push(e);
    }
    for e in ANALYTICS_CATALOG {
        v.push(e);
    }
    for e in SOCIAL_CATALOG {
        v.push(e);
    }
    for e in DESIGN_CATALOG {
        v.push(e);
    }
    for e in MAPS_CATALOG {
        v.push(e);
    }
    for e in UTILITY_CATALOG {
        v.push(e);
    }
    for e in SKILL_CATALOG {
        v.push(e);
    }
    v
}
